# テンプレートを読み込み
include:
  - project: 'qwerty01211/cicd-template'
    ref: main
    file: '/templates/.gitlab-ci-template.yml'

echo:
  extends: .template-job
  variables:
    TEST_VARIABLE: 'Message by cicd-sample'
